### ISSUE TITLE
git: `v6.0.0-alpha.5` does not compile for `GOOS=js`

### ISSUE THREAD

**Issue by iwahbe** [go-git/go-git#2417]
### Bug Description

The top level `git` (`github.com/go-git/go-git`) package does not compile for `GOOS=js GOARCH=wasm`.

### go-git Version

v6.0.0-alpha.5

### Steps to Reproduce

Checkout this repo on `main` (currently at 0f3a0a2c25513f2666ac9b88a6745f7b2382f572):

```
𝛌 GOOS=js GOARCH=wasm go build .
# github.com/go-git/go-git/v6
./worktree.go:85:19: undefined: osfs.FromRoot
```

### Additional Information

- This worked in `v6.0.0-alpha.4`.
- The break was introduced in https://github.com/go-git/go-git/pull/2259.
- Should there be interest, I have a PR open to address the problem: https://github.com/go-git/go-git/pull/2406.
